### ISSUE TITLE
Can't find service after installing via HACS

### ISSUE THREAD

**Issue by sdholden28** [dannytrigo/ha-pipup#2]
I've installed the integration via HACS after adding the repository, https://github.com/dannytrigo/ha-pipup. I cannot find the service under developer settings. I have restarted HA. I'm running 2024.12.5. I don't see anything in the logs regarding pipup unfortunately. Is there something I missed? How can I help debug?

**Comment by artek79** [comment]
same(

**Comment by goprojojo** [comment]
Same here. I was wondering if someone has figured it out?

**Comment by dannytrigo** [comment]
I'll try to take a look this week, but I personally kind of gave up on PiPUp because it couldn't play video at the same time another app was playing video on the same device

**Comment by sdholden28** [comment]
PipUp can do that, if you use the right version of the APK. I had it working as you describe for a long time. With that said, I've moved over to TvOverlay and much prefer it. https://github.com/gugutab/TvOverlay. A similar integration to this one would be very helpful for TvOverlay as well, as the service calls are similar.

**Comment by artek79** [comment]
I've moved over to TvOverlay and much prefer it. https://github.com/gugutab/TvOverlay.

Can TvOverlay show video from camera?)
PiPUp can...

**Comment by sdholden28** [comment]
Yes. It can play rtsp feeds directly. Its also available in the play store and there's no adb commands or anything like that, so its much easier to setup and use. There's also decent documentation available at the github link. I use it to show the video doorbell on TVs whenever someone is at the door, and I use it to show the camera in the baby's room on demand. Here's an example service call:

```
action: notify.tvoverlaylrshield
data:
  title: Baby Vision®
  message: "null"
  data:
    appTitle: Home Assistant
    largeIcon: mdi:human-greeting-variant
    corner: bottom_end
    seconds: 60
    video: rtsp://192.168.XX.XX:8554/nurseryrtc
continue_on_error: true
```
